use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    aoc2023::day3::run()?;

    Ok(())
}
